# Generated by Django 3.1.3 on 2021-02-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('display_name', models.TextField(default=None, verbose_name="Nom d'affichage")),
                ('real_url', models.BooleanField(blank=True, default=None, verbose_name='Url')),
                ('description', models.BooleanField(blank=True, default=None, null=True, verbose_name='description')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
