# Generated by Django 3.1.3 on 2021-02-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitesModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='Nom du site')),
                ('url', models.TextField(default='https://google.com', verbose_name='Url du site')),
            ],
            options={
                'ordering': ('-name',),
                'abstract': False,
            },
        ),
    ]
